<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mana</string>
	</array>
	<key>name</key>
	<string>Mana</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#blockComment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#lineComment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#lineComment2</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#quotedString</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#quotedChar</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(namespace|type|trait|instance|where|case|of)\b</string>
			<key>name</key>
			<string>keyword.mana</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>blockComment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.mana</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#blockComment</string>
				</dict>
			</array>
		</dict>
		<key>escapedChar</key>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.character.escape.mana</string>
		</dict>
		<key>lineComment</key>
		<dict>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment.line.mana</string>
		</dict>
		<key>lineComment2</key>
		<dict>
			<key>match</key>
			<string>--.*$</string>
			<key>name</key>
			<string>comment.line.mana</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>match</key>
			<string>[-*/+~&lt;&gt;$|^&amp;%!@;.:=\\]</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<key>quotedChar</key>
		<dict>
			<key>begin</key>
			<string>\'</string>
			<key>end</key>
			<string>\'</string>
			<key>name</key>
			<string>string.quoted.single.mana</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escapedChar</string>
				</dict>
			</array>
		</dict>
		<key>quotedString</key>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.mana</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escapedChar</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mana</string>
	<key>uuid</key>
	<string>c34dd756-f190-4215-9b89-6fb8153f45e7</string>
</dict>
</plist>
